easy_admin:
    site_name: 'Admiral'
    design:
        assets:
            css:
                - '/styles/styles.css'
    entities:
        # List the entity class name you want to manage
        Archetype:
            class: App\Entity\Archetype
            help: 'An Archetype is a template for a project. Projects will be updateable from their Archetype.'
            label: 'Site Archetype'
            show:
                fields: ['name', 'gitUri', 'updateBranch', 'updateOperation', 'projects']
            list:
                fields: ['name', 'gitUri', 'projects']
                actions: ['show', 'edit', 'delete']
                collapse_actions: true
            form:
                fields: ['name', 'gitUri', 'updateBranch', 'updateOperation']
        Project:
            class: App\Entity\Project
            controller: App\Controller\ProjectController
            help: 'A Project on Platform.sh'
            show:
                fields:
                    - 'title'
                    - { property: 'projectId', label: 'Platform.sh Project', template: 'admin/psh_project_id.html.twig' }
                    - 'region'
                    - 'archetype'
                    - { property: 'updateEnvironment', label: 'Update branch', type: string, template: 'admin/update_environment.html.twig' }
                    - { property: 'planSize', label: 'Plan size', type: 'string' }
                    - { property: 'recentActivities', label: 'Recent Activities', template: 'admin/recent_activities.html.twig' }
            list:
                fields:
                    - 'title'
                    - { property: 'projectId', label: 'Platform.sh Project', template: 'admin/psh_project_id.html.twig' }
                    - 'region'
                    - 'archetype'
                    - { property: 'updateEnvironment', label: 'Preview Updates', template: 'admin/update_environment.html.twig' }
                actions: ['show', 'edit', 'update', 'merge_update', 'backup', 'delete']
                collapse_actions: true
                batch_actions: ['update', 'merge_update', 'backup', 'delete']
            new:
              fields:
                - 'title'
                - { property: 'region', label: 'Region', type: 'App\Form\Type\RegionType' }
                - 'archetype'
            edit:
              fields: ['title']

