easy_admin:
    site_name: 'Flotilla'
    entities:
        # List the entity class name you want to manage
        Archetype:
            class: App\Entity\Archetype
            help: 'An Archetype is a template for a project. Projects will be updateable from their Archetype.'
            label: 'Site Archetype'
            show:
                fields: ['name', 'gitUri', 'updateBranch', 'updateOperation']
            list:
                fields: ['id', 'name', 'gitUri', 'projects']
                actions: ['show', 'edit', 'delete']
                collapse_actions: true
            form:
                fields: ['name', 'gitUri', 'updateBranch', 'updateOperation']
        Project:
            class: App\Entity\Project
            controller: App\Controller\ProjectController
            help: 'A Project on Platform.sh'
            show:
                fields: ['title', 'projectId', 'region', 'archetype']
            list:
                actions: ['show', 'edit', 'update', 'delete']
                collapse_actions: true
                batch_actions: ['update']
            new:
              fields: ['title', 'region', 'archetype']
            edit:
              fields: ['title']
