easy_admin:
    site_name: 'Flotilla'
    entities:
        # List the entity class name you want to manage
        Archetype:
            class: App\Entity\Archetype
            help: 'An Archetype is a template for a project. Projects will be updateable from their Archetype.'
            label: 'Site Archetype'
            list:
                fields: ['id', 'name', 'gitUri', 'projects']
            form:
                fields: ['name', 'gitUri', 'updateBranch', 'updateOperation']
#        - App\Entity\Project
